DROP TABLE IF EXISTS MANAGER.ROULETTE;
DROP TABLE IF EXISTS MANAGER.STATE;
DROP TABLE IF EXISTS MANAGER.BET_USER;
DROP TABLE IF EXISTS MANAGER.STATE_BET;


CREATE TABLE MANAGER.ROULETTE (
  ID_ROULETTE INT PRIMARY KEY,  
  ID_STATE INT
);

CREATE TABLE MANAGER.STATE (
  ID_STATE INT PRIMARY KEY,  
  DESCRIPTION VARCHAR(30)
);

CREATE TABLE MANAGER.BET_USER(
	ID_BET INT PRIMARY KEY,
	ID_ROULETTE INT,
	ID_STATEBET INT,
	ID_GAMBLER INT,
	BET VARCHAR(30),
	AMOUNT DECIMAL(10,2)
);

CREATE TABLE MANAGER.STATE_BET(
	ID_STATEBET INT PRIMARY KEY,
	DESCRIPTION VARCHAR(30)
);

ALTER TABLE MANAGER.ROULETTE ADD CONSTRAINT FK_ID_STATE
FOREIGN KEY (ID_STATE) REFERENCES MANAGER.STATE(ID_STATE);

ALTER TABLE MANAGER.BET_USER ADD CONSTRAINT FK_ID_ROULETTE
FOREIGN KEY (ID_ROULETTE) REFERENCES MANAGER.ROULETTE(ID_ROULETTE);

ALTER TABLE MANAGER.BET_USER ADD CONSTRAINT FK_ID_STATE_BET
FOREIGN KEY (ID_STATEBET) REFERENCES MANAGER.STATE_BET(ID_STATEBET);