DROP TABLE IF EXISTS MANAGER.ROULETTE;
DROP TABLE IF EXISTS MANAGER.STATE;

CREATE TABLE MANAGER.ROULETTE (
  ID_ROULETTE INT PRIMARY KEY,  
  ID_STATE VARCHAR(30)
);

CREATE TABLE MANAGER.STATE (
  ID_STATE INT PRIMARY KEY,  
  DESCRIPTION VARCHAR(30)
);

ALTER TABLE MANAGER.ROULETTE ADD CONSTRAINT FK_ID_STATE
FOREIGN KEY (ID_STATE) REFERENCES MANAGER.STATE(ID_STATE);